.PHONY: *

all: install config

install:
	sudo dnf install -y git

config:
	git config --global user.name axgz
	git config --global user.email axgz@local
	git config --global core.pager cat
	git config --global init.defaultBranch main

