.PHONY: *

all: stow install

stow:
	stow --adopt -t ~/.config hypr.stpkg

install:
	#sudo dnf install -y hyprland mako rofi
	#sudo dnf install -y --releasever=41 hypridle hyprlock hyprpaper hyprpicker

